/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work-orders/{id}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    cursor?: string;
                    pageSize?: number;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ActivityPage"];
                        "application/json": components["schemas"]["ActivityPage"];
                        "text/json": components["schemas"]["ActivityPage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work-orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Search?: string;
                    CustomerId?: string;
                    LocationId?: string;
                    TechnicianId?: string;
                    Unassigned?: boolean;
                    ServiceType?: components["schemas"]["ServiceType"];
                    Status?: components["schemas"]["WorkOrderStatus"][];
                    SlaStatus?: components["schemas"]["SlaState"];
                    CreatedFrom?: string;
                    CreatedTo?: string;
                    OpenOnly?: boolean;
                    Sort?: string;
                    Page?: number;
                    PageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WorkOrderPage"];
                        "application/json": components["schemas"]["WorkOrderPage"];
                        "text/json": components["schemas"]["WorkOrderPage"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ValidationProblemDetails"];
                        "application/json": components["schemas"]["ValidationProblemDetails"];
                        "text/json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateWorkOrderRequest"];
                    "text/json": components["schemas"]["CreateWorkOrderRequest"];
                    "application/*+json": components["schemas"]["CreateWorkOrderRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WorkOrderDetail"];
                        "application/json": components["schemas"]["WorkOrderDetail"];
                        "text/json": components["schemas"]["WorkOrderDetail"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ValidationProblemDetails"];
                        "application/json": components["schemas"]["ValidationProblemDetails"];
                        "text/json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work-orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WorkOrderDetail"];
                        "application/json": components["schemas"]["WorkOrderDetail"];
                        "text/json": components["schemas"]["WorkOrderDetail"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CorrectDetailsRequest"];
                    "text/json": components["schemas"]["CorrectDetailsRequest"];
                    "application/*+json": components["schemas"]["CorrectDetailsRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WorkOrderDetail"];
                        "application/json": components["schemas"]["WorkOrderDetail"];
                        "text/json": components["schemas"]["WorkOrderDetail"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/work-orders/{id}/assignment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AssignmentRequest"];
                    "text/json": components["schemas"]["AssignmentRequest"];
                    "application/*+json": components["schemas"]["AssignmentRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WorkOrderDetail"];
                        "application/json": components["schemas"]["WorkOrderDetail"];
                        "text/json": components["schemas"]["WorkOrderDetail"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work-orders/{id}/status-transitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["StatusTransitionRequest"];
                    "text/json": components["schemas"]["StatusTransitionRequest"];
                    "application/*+json": components["schemas"]["StatusTransitionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WorkOrderDetail"];
                        "application/json": components["schemas"]["WorkOrderDetail"];
                        "text/json": components["schemas"]["WorkOrderDetail"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/technicians": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TechnicianOption"][];
                        "application/json": components["schemas"]["TechnicianOption"][];
                        "text/json": components["schemas"]["TechnicianOption"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CustomerOption"][];
                        "application/json": components["schemas"]["CustomerOption"][];
                        "text/json": components["schemas"]["CustomerOption"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{id}/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LocationOption"][];
                        "application/json": components["schemas"]["LocationOption"][];
                        "text/json": components["schemas"]["LocationOption"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reference-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CreationOptions"];
                        "application/json": components["schemas"]["CreationOptions"];
                        "text/json": components["schemas"]["CreationOptions"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    StartDate?: string;
                    EndDateExclusive?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DashboardResponse"];
                        "application/json": components["schemas"]["DashboardResponse"];
                        "text/json": components["schemas"]["DashboardResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ValidationProblemDetails"];
                        "application/json": components["schemas"]["ValidationProblemDetails"];
                        "text/json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CsrfResponse"];
                        "application/json": components["schemas"]["CsrfResponse"];
                        "text/json": components["schemas"]["CsrfResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                    "text/json": components["schemas"]["LoginRequest"];
                    "application/*+json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SessionResponse"];
                        "application/json": components["schemas"]["SessionResponse"];
                        "text/json": components["schemas"]["SessionResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ActivityItem: {
            /** Format: uuid */
            id: string;
            eventType: components["schemas"]["WorkOrderEventType"];
            /** Format: uuid */
            actorUserId: string;
            actorName: string;
            /** Format: date-time */
            effectiveAt: string;
            /** Format: date-time */
            recordedAt: string;
            changes: null | components["schemas"]["JsonElement"];
        };
        ActivityPage: {
            items: components["schemas"]["ActivityItem"][];
            nextCursor: null | string;
        };
        AssignmentRequest: {
            /** Format: uuid */
            technicianId: null | string;
            /** Format: int32 */
            expectedRevision?: null | number;
        };
        CorrectDetailsRequest: {
            title: string;
            description: string;
            /** Format: int32 */
            expectedRevision?: null | number;
        };
        CreateWorkOrderRequest: {
            /** Format: uuid */
            customerId: null | string;
            /** Format: uuid */
            locationId: null | string;
            serviceType: null | components["schemas"]["ServiceType"];
            priority: null | components["schemas"]["Priority"];
            title: string;
            description: string;
        };
        CreationOptions: {
            serviceTypes: components["schemas"]["ServiceOption"][];
            priorities: components["schemas"]["PriorityOption"][];
        };
        CsrfResponse: {
            token: string;
        };
        CurrentOperations: {
            /** Format: int32 */
            open: number;
            /** Format: int32 */
            new: number;
            /** Format: int32 */
            assigned: number;
            /** Format: int32 */
            inProgress: number;
            /** Format: int32 */
            onHold: number;
            /** Format: int32 */
            good: number;
            /** Format: int32 */
            atRisk: number;
            /** Format: int32 */
            breached: number;
        };
        CustomerOption: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        DashboardResponse: {
            /** Format: date-time */
            evaluatedAt: string;
            timeZone: string;
            current: components["schemas"]["CurrentOperations"];
            workload: components["schemas"]["TechnicianWorkload"][];
            period: components["schemas"]["PeriodPerformance"];
        };
        JsonElement: unknown;
        LocationOption: {
            /** Format: uuid */
            id: string;
            name: string;
            address: string;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        PeriodPerformance: {
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDateExclusive: string;
            /** Format: date-time */
            fromUtc: string;
            /** Format: date-time */
            toUtc: string;
            /** Format: int32 */
            completed: number;
            /** Format: int32 */
            met: number;
            /** Format: int32 */
            missed: number;
            /** Format: double */
            compliancePercent: null | number;
        };
        /** @enum {unknown} */
        Priority: "Critical" | "High" | "Normal" | "Low";
        PriorityOption: {
            code: components["schemas"]["Priority"];
            label: string;
            /** Format: int32 */
            slaDurationMinutes: number;
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
        };
        ServiceOption: {
            code: components["schemas"]["ServiceType"];
            label: string;
        };
        /** @enum {unknown} */
        ServiceType: "HVAC" | "Electrical" | "Plumbing" | "Equipment" | "GeneralMaintenance";
        SessionResponse: {
            /** Format: uuid */
            id: string;
            displayName: string;
            email: string;
            roles: string[];
        };
        /** @enum {unknown} */
        SlaState: "Good" | "AtRisk" | "Breached" | null;
        StatusTransitionRequest: {
            targetStatus: null | components["schemas"]["WorkOrderStatus"];
            reason?: null | string;
            summary?: null | string;
            /** Format: int32 */
            expectedRevision?: null | number;
        };
        TechnicianOption: {
            /** Format: uuid */
            id: string;
            displayName: string;
            isActive: boolean;
        };
        TechnicianWorkload: {
            /** Format: uuid */
            technicianId: null | string;
            technicianName: string;
            /** Format: int32 */
            openCount: number;
        };
        ValidationProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
            errors?: {
                [key: string]: string[];
            };
        };
        WorkOrderDetail: {
            /** Format: uuid */
            id: string;
            number: string;
            title: string;
            description: string;
            /** Format: uuid */
            customerId: string;
            customerName: string;
            /** Format: uuid */
            locationId: string;
            locationName: string;
            locationAddress: string;
            serviceType: components["schemas"]["ServiceType"];
            priority: components["schemas"]["Priority"];
            status: components["schemas"]["WorkOrderStatus"];
            /** Format: date-time */
            createdAt: string;
            /** Format: uuid */
            createdByUserId: string;
            /** Format: int32 */
            slaDurationMinutes: number;
            /** Format: date-time */
            slaAtRiskAt: string;
            /** Format: date-time */
            slaDeadlineAt: string;
            slaState: null | components["schemas"]["SlaState"];
            /** Format: int32 */
            revision: number;
            /** Format: date-time */
            evaluatedAt: string;
            /** Format: uuid */
            technicianId: null | string;
            technicianName: null | string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            completedAt: null | string;
            /** Format: date-time */
            cancelledAt: null | string;
            holdReason: null | string;
            resolutionSummary: null | string;
            cancellationReason: null | string;
        };
        /** @enum {unknown} */
        WorkOrderEventType: "Created" | "Assigned" | "Reassigned" | "Unassigned" | "DetailsCorrected" | "Started" | "PlacedOnHold" | "Resumed" | "Completed" | "Cancelled";
        WorkOrderPage: {
            items: components["schemas"]["WorkOrderSummary"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int32 */
            totalCount: number;
            /** Format: date-time */
            evaluatedAt: string;
        };
        /** @enum {unknown} */
        WorkOrderStatus: "New" | "Assigned" | "InProgress" | "OnHold" | "Completed" | "Cancelled";
        WorkOrderSummary: {
            /** Format: uuid */
            id: string;
            number: string;
            title: string;
            /** Format: uuid */
            customerId: string;
            customerName: string;
            /** Format: uuid */
            locationId: string;
            locationName: string;
            serviceType: components["schemas"]["ServiceType"];
            priority: components["schemas"]["Priority"];
            status: components["schemas"]["WorkOrderStatus"];
            /** Format: uuid */
            technicianId?: null | string;
            technicianName?: null | string;
            slaState: null | components["schemas"]["SlaState"];
            /** Format: date-time */
            deadline: string;
            /** Format: date-time */
            createdAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
