/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work-orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Search?: string;
                    CustomerId?: string;
                    LocationId?: string;
                    ServiceType?: components["schemas"]["ServiceType"];
                    Status?: components["schemas"]["WorkOrderStatus"][];
                    SlaStatus?: components["schemas"]["SlaState"];
                    CreatedFrom?: string;
                    CreatedTo?: string;
                    OpenOnly?: boolean;
                    Sort?: string;
                    Page?: number;
                    PageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WorkOrderPage"];
                        "application/json": components["schemas"]["WorkOrderPage"];
                        "text/json": components["schemas"]["WorkOrderPage"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ValidationProblemDetails"];
                        "application/json": components["schemas"]["ValidationProblemDetails"];
                        "text/json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateWorkOrderRequest"];
                    "text/json": components["schemas"]["CreateWorkOrderRequest"];
                    "application/*+json": components["schemas"]["CreateWorkOrderRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WorkOrderDetail"];
                        "application/json": components["schemas"]["WorkOrderDetail"];
                        "text/json": components["schemas"]["WorkOrderDetail"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ValidationProblemDetails"];
                        "application/json": components["schemas"]["ValidationProblemDetails"];
                        "text/json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/work-orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WorkOrderDetail"];
                        "application/json": components["schemas"]["WorkOrderDetail"];
                        "text/json": components["schemas"]["WorkOrderDetail"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CustomerOption"][];
                        "application/json": components["schemas"]["CustomerOption"][];
                        "text/json": components["schemas"]["CustomerOption"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{id}/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LocationOption"][];
                        "application/json": components["schemas"]["LocationOption"][];
                        "text/json": components["schemas"]["LocationOption"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reference-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CreationOptions"];
                        "application/json": components["schemas"]["CreationOptions"];
                        "text/json": components["schemas"]["CreationOptions"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CsrfResponse"];
                        "application/json": components["schemas"]["CsrfResponse"];
                        "text/json": components["schemas"]["CsrfResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                    "text/json": components["schemas"]["LoginRequest"];
                    "application/*+json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SessionResponse"];
                        "application/json": components["schemas"]["SessionResponse"];
                        "text/json": components["schemas"]["SessionResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateWorkOrderRequest: {
            /** Format: uuid */
            customerId: null | string;
            /** Format: uuid */
            locationId: null | string;
            serviceType: null | components["schemas"]["ServiceType"];
            priority: null | components["schemas"]["Priority"];
            title: string;
            description: string;
        };
        CreationOptions: {
            serviceTypes: components["schemas"]["ServiceOption"][];
            priorities: components["schemas"]["PriorityOption"][];
        };
        CsrfResponse: {
            token: string;
        };
        CustomerOption: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        LocationOption: {
            /** Format: uuid */
            id: string;
            name: string;
            address: string;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        /** @enum {unknown} */
        Priority: "Critical" | "High" | "Normal" | "Low";
        PriorityOption: {
            code: components["schemas"]["Priority"];
            label: string;
            /** Format: int32 */
            slaDurationMinutes: number;
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
        };
        ServiceOption: {
            code: components["schemas"]["ServiceType"];
            label: string;
        };
        /** @enum {unknown} */
        ServiceType: "HVAC" | "Electrical" | "Plumbing" | "Equipment" | "GeneralMaintenance";
        SessionResponse: {
            /** Format: uuid */
            id: string;
            displayName: string;
            email: string;
            roles: string[];
        };
        /** @enum {unknown} */
        SlaState: "Good" | "AtRisk" | "Breached";
        ValidationProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
            errors?: {
                [key: string]: string[];
            };
        };
        WorkOrderDetail: {
            /** Format: uuid */
            id: string;
            number: string;
            title: string;
            description: string;
            /** Format: uuid */
            customerId: string;
            customerName: string;
            /** Format: uuid */
            locationId: string;
            locationName: string;
            locationAddress: string;
            serviceType: components["schemas"]["ServiceType"];
            priority: components["schemas"]["Priority"];
            status: components["schemas"]["WorkOrderStatus"];
            /** Format: date-time */
            createdAt: string;
            /** Format: uuid */
            createdByUserId: string;
            /** Format: int32 */
            slaDurationMinutes: number;
            /** Format: date-time */
            slaAtRiskAt: string;
            /** Format: date-time */
            slaDeadlineAt: string;
            slaState: components["schemas"]["SlaState"];
            /** Format: int32 */
            revision: number;
            /** Format: date-time */
            evaluatedAt: string;
        };
        WorkOrderPage: {
            items: components["schemas"]["WorkOrderSummary"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int32 */
            totalCount: number;
            /** Format: date-time */
            evaluatedAt: string;
        };
        /** @enum {unknown} */
        WorkOrderStatus: "New";
        WorkOrderSummary: {
            /** Format: uuid */
            id: string;
            number: string;
            title: string;
            /** Format: uuid */
            customerId: string;
            customerName: string;
            /** Format: uuid */
            locationId: string;
            locationName: string;
            serviceType: components["schemas"]["ServiceType"];
            priority: components["schemas"]["Priority"];
            status: components["schemas"]["WorkOrderStatus"];
            slaState: components["schemas"]["SlaState"];
            /** Format: date-time */
            deadline: string;
            /** Format: date-time */
            createdAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
